### ISSUE TITLE
C2-12828-1 crash when starting and how to do fresh reinstall of the autoplugin2? (Where are the cache, for example, languages autoplugin2 use located?)

### ISSUE THREAD

**Issue by Jimmisama** [ONElua/AutoPlugin2#174] opened 2022-07-26 14:22 UTC
It used to work fine on SD2Vita etc. Today I have a new memory card so I tried to install autoplugin2 on that new memory card. The app started fine and it looked like it's downloading some additional contents including "Chinese" language, but failed half way (probably due to network error). At first the app works but when switching to Chinese, the texts were just blank and empty.
I tried to fix this by reinstall the autoplugin 2, refresh database, and I got C2-12828-1 now and the app won't even start now.
After I got the C2-12828-1 I also try to reinstall autoplugin 1 and update from it, however the autoplugin2 app still crashes on start. The autoplugin1 app didn't crash. How do I completely uninstall autoplugin2 so that it will start to download "contents" again when I reinstall it next time? Please help me, thank you. I want to give it another try after cleaning the cache autoplugin2 uses. Where are those files located?

[psp2core-1658845748-0x00002e33eb-eboot.bin.zip](https://github.com/ONElua/AutoPlugin2/files/9190678/psp2core-1658845748-0x00002e33eb-eboot.bin.zip)

**Comment by ONElua** [comment] 2022-07-26 21:03
Delete
ux0:data/autoplugin2

**Comment by Jimmisama** [comment] 2022-07-29 05:21
> Delete
> ux0:data/autoplugin2

It works, thanks.

**Comment by hedhehd** [comment] 2022-07-29 09:42
I guess the issue is solved then. You can close it

**Closed** 2022-07-29 09:43 UTC
