### ISSUE TITLE
LBP server patch doesn't check game card when looking for games.

### ISSUE THREAD

**Issue by StarflightRaven** [ONElua/AutoPlugin2#267] opened 2024-08-07 21:44 UTC
![20240807_164144](https://github.com/user-attachments/assets/d14313f3-4ec9-4994-b3ae-0e7a0c59a6c4)
![20240807_164108](https://github.com/user-attachments/assets/cd460795-cead-4ad8-aadf-e70452685f53)
![7d5219bc-8465-446b-8d38-78b18de26a07](https://github.com/user-attachments/assets/a99fede9-a377-426a-9c68-53898571a5c6)

**Comment by ONElua** [comment] 2024-08-08 00:41
Do you have the game physically?

**Comment by StarflightGamin** [comment] 2024-08-08 00:43
Yes

**Comment by ONElua** [comment] 2024-08-08 01:33
Please install Onemenu and show me the game information

**Comment by StarflightGamin** [comment] 2024-08-12 18:53
Sorry for taking for

**Comment by StarflightGamin** [comment] 2024-08-23 16:57
I still have no idea what to do (Also sorry for closing, I'm relatively new to Github)

**Comment by jvyden** [comment] 2024-09-05 20:40
Hi, I'm from LittleBigRefresh. We're seeing more reports of this happening:

![image](https://github.com/user-attachments/assets/ff2cd573-2266-496c-be33-8046f3fa0981)
![image](https://github.com/user-attachments/assets/63a2170c-93d9-455d-89e1-e605fde856a8)

I'll ask the first user to try to grab OneMenu. I don't have a Vita myself so I can't reproduce this haha

**Comment by jvyden** [comment] 2024-09-05 21:15
They responded with this:
![image](https://github.com/user-attachments/assets/26dde654-1d73-49bc-a9b5-e5162fb73a9d)
![IMG_3041](https://github.com/user-attachments/assets/e8d9f67e-2474-4a61-8021-9a3707229bca)

**Comment by SomeonesGarbage** [comment] 2024-09-09 04:38
Hey yall! Been having the same issue with my european cartridge like @StarflightGamin. The cartridge is on 1.22 and is in the vita. I can send a video if needed. (also nothing shows up in onemenu)

**Comment by SomeonesGarbage** [comment] 2024-09-09 16:16
Update: Installing Allefresher manually seems to work. (Allefresher-vita.suprx on LittleBigRefresh's github page)

**Comment by ONElua** [comment] 2024-11-19 22:31
Hi, i need your help ...
For testing

**Comment by ONElua** [comment] 2024-12-22 23:37
Netx Update

**Comment by ONElua** [comment] 2024-12-24 23:31
https://github.com/ONElua/AutoPlugin2/releases/tag/2.13

**Closed by ONElua** 2024-12-24 23:31 UTC
